### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by GibsonRuitiari**
## Updated Readme

Improved the tone, tense and words used in readme.md.

### CODE REVIEW

**Comment by jisungbin** [comment]
👀

**Comment by jisungbin** [comment]
Hmmm, CI failed, but I think there is a problem with our CI. Your PR is a simple document modification, so it doesn't directly affect the code. In other words, it doesn't matter if the CI fails (I think 😅). Thanks for the first contribution!

**Review by jisungbin — APPROVED** [review]

**Comment by jisungbin** [comment]
Also, I'm not good at English, so I needed a contribution like this. 🙌 ❤️

**Comment by GibsonRuitiari** [comment]
The CI is failing because there are no secret keys. I think you need to make the default secret keys available during the CI builds or do away with it all together haha.
Anyway, you are welcome, friend.

**Comment by jisungbin** [comment]
> The CI is failing because there are no secret keys. I think you need to make the default secret keys available during the CI builds or do away with it all together haha. Anyway, you are welcome, friend.

That's right, I saw the CI log. I will fix this problem soon. thank you!

**Pull request merged**
